name: build github-artifact-fetcher

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: go modules cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: build
        run: go build -o github-artifact-fetcher cmd/main.go
      - name: store binary
        uses: actions/upload-artifact@v3
        with:
          name: github-artifact-fetcher.zip
          path: github-artifact-fetcher
